name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'gradle'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Verify formatting
      run: flutter format --set-exit-if-changed .
    
    - name: Analyze project source
      run: flutter analyze
    
    - name: Run tests
      run: flutter test
    
    - name: Build APK
      run: |
        flutter config --android-sdk $ANDROID_HOME
        flutter build apk --release
    
    - name: Generate build number
      id: buildnumber
      run: echo "::set-output name=buildnumber::$(date +'%Y%m%d.%H%M')"
    
    - name: Rename APK
      run: |
        mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/adsd-maintenance-${{ steps.buildnumber.outputs.buildnumber }}.apk
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/adsd-maintenance-${{ steps.buildnumber.outputs.buildnumber }}.apk
        retention-days: 30 